name: Docker Actions

on:
  pull_request:
    types: ["labeled"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-action
        with:
          firstGreeting: "Learning Lab User"

      - name: meow
        uses: ./.github/actions/cat-facts
